/**
 * @author Puffer
 * @createdAt 12/19/2022
 * @updatedAt 12/19/2022
 **/

export const STORE_KEYS = {
  id: {
    enterprises: "enterprises",
    step: "step",
  },
};

export const STEP = {
  INDEX: "INDEX",

  CREATE_ENTERPRISE_INPUT: "CREATE_ENTERPRISE_INPUT",
  CREATE_SHAREHOLDERS_VIEW: "CREATE_SHAREHOLDERS_VIEW",
  CREATE_SHAREHOLDER_ADD: "CREATE_SHAREHOLDER_ADD",
  CREATE_SHAREHOLDER_EDIT: "CREATE_SHAREHOLDER_EDIT",
  CREATE_ADMINS_VIEW: "CREATE_ADMINS_VIEW",
  CREATE_ADMIN_ADD: "CREATE_ADMIN_ADD",
  CREATE_ADMIN_EDIT: "CREATE_ADMIN_EDIT",
  CREATE_PROCESSING: "CREATE_PROCESSING",
  CREATE_SUCCESSED: "CREATE_SUCCESSED",

  SHAREHOLDER_ADD: "SHAREHOLDER_ADD",

  ADMIN_ADD: "ADMIN_ADD",
  ADMIN_EDIT: "ADMIN_EDIT",

  SETTING_COMPANY_REVIEW: "SETTING_COMPANY_REVIEW",
  SETTING_COMPANY_EDIT: "SETTING_COMPANY_EDIT",

  PROPOSAL_ADMIN: "PROPOSAL_ADMIN",
  PROPOSAL_SHAREHOLDER: "PROPOSAL_SHAREHOLDER",

  DASHBOARD_ADMIN_EDIT: "DASHBOARD_ADMIN_EDIT",
  DASHBOARD_MEMBERS: "DASHBOARD_MEMBERS",
  DASHBOARD_MEMBERS_ADMIN_EDIT: "DASHBOARD_MEMBERS_ADMIN_EDIT",
  DASHBOARD_MEMBERS_SHAREHOLDER_EDIT: "DASHBOARD_MEMBERS_SHAREHOLDER_EDIT",

  DASHBOARD_TRADE_ADD: "DASHBOARD_TRADE_ADD",
  DASHBOARD_TRADE_ORDERBOOK: "DASHBOARD_TRADE_ORDERBOOK",
};
